config/routes.rb
Rails.application.routes.draw do 

  get "contact/new" => "contact/new"
  post "contact/confirm" => "contact/confirm"
  post "contact/thanks" => "contact/thanks"

  devise_for :users

  resources :users, only: [:show]

  resources :posts, only: [:create, :new, :edit, :show, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  root "home#top"
  get "home/usa" => "home#usa"
  get "home/uk" => "home#uk"
  get "home/canada" => "home#canada"
  get "home/australia" => "home#australia"
  get "home/newzealand" => "home#newzealand"
  get "home/southafrica" => "home#southafrica"
  get "home/malta" => "home#malta"
  get "home/philippines" => "home#philippines"
  get "home/terms" => "home#terms"
  get "home/privacy" => "home#privacy"
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  mount_uploader :image_name1, ImageName1Uploader

  validates :country, {presence:true}
  validates :howlong, {presence:true}
  validates :schoolname, {presence:true}
  validates :city, {presence:true}
  validates :money, {presence:true}
  validates :user_id, {presence:true}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, {only:[:new, :create, :edit, :update, :destroy]}
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to(post_path(@post.id))
    else
      render("posts/new")
    end
  end
  
  def show
    @post = Post.find_by(id: params[:id])
    @user = @post.user
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :asc)
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to(root_path)
    else
      render("posts/edit")
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to(root_path)
  end

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != current_user.id
      flash[:notice] ="権限がありません"
      redirect_to(root_path)
    end
  end

  private
   def post_params
    params.require(:post).permit(:image_name1, :country, :howlong, :visa, :schoolname, :city, :money, :agent, :necessity).merge(user_id: current_user.id)
   end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_errors.html.erb
<% if post.errors.any? %>
    <div class="post-errors">
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/posts/edit.html.erb
<% @page_title = "Post Edit" %>
<header>
  <div class="header-logo">
    <ul class="header-menu for-post">
      <li>
        <%= link_to("Top", root_path) %>
      </li>
      <li>
        <%= link_to("Back", :back) %>
      </li>
      <li>
        <%= link_to("Logout", destroy_user_session_path, {method: "delete"}) %>
      </li>
    </ul>
  </div>
</header>
<div class="post-container">
  <%= render partial: 'posts/errors', locals: { post:@post } %>
  <%= form_with model: @post do |f| %>
    <div class="form-content">
      <div class="post-photo">
        <%if @post.image_name1? %>
          <%= image_tag @post.image_name1.url, id: "preview" %>
        <% else %>
          <%= image_tag "/no_image1.png" %>
        <% end %>
        <%= f.file_field :image_name1, id: "post_image" %>
      </div>
      <div class="without-photo">
        <div class="county form">
          <%= f.select :country, [["USA", "USA"], ["UK", "UK"], ["Canada", "Canada"], ["Australia", "Australia"], ["NewZealand", "Newzealand"], ["SouthAfrica", "SouthAfrica"], ["Malta", "Malta"], ["thePhilippines", "thePhilippines"]] %>
        </div>
        <div class="city form">
          <%= f.text_field :city, placeholder: "地域" %>
        </div>
        <div class="howlong form">
          <%= f.text_field :howlong, placeholder: "期間" %>
        </div>
        <div class="visa form">
          <%= f.text_field :visa, placeholder: "ビザの種類" %>
        </div>
        <div class="money form">
          <%= f.text_field :money, placeholder: "費用" %>
        </div>
        <div class="school form">
          <%= f.text_field :schoolname, placeholder: "学校名" %>
        </div>
        <div class="agent form">
          <%= f.text_field :agent, placeholder: "エージェント" %>
        </div>
        <div class="necessity form">
            <%= f.text_field :necessity, placeholder: "必需品" %>
        </div>
      </div>
      <div class="submit">
        <%= f.submit "Share", class:"submit-form"%>
      </div>
    </div>
  <% end %>
    <div class="post-delete">
      <%= link_to("delete post", post_path, {method:"delete", data: { confirm: "削除しますか？"}}) %>
    </div>
</div>

app/views/posts/new.html.erb
<% @page_title = "New Post"%>
<header>
  <div class="header-logo">
    <ul class="header-menu for-post">
      <li>
        <%= link_to("Top", root_path) %>
      </li>
      <li>
        <%= link_to("Back", :back) %>
      </li>
      <li>
        <%= link_to("Logout", destroy_user_session_path, {method: "delete"}) %>
      </li>
    </ul>
  </div>
</header>
<div class="post-container">
  <%= render partial: 'posts/errors', locals: { post:@post } %>
  <%= form_with model: @post do |f| %>
    <div class="form-content">
      <div class="post-photo">
        <%= image_tag "/no_image1.png", id: "preview" %>
        <%= f.file_field :image_name1, id: "post_image" %>
      </div>
      <div class="without-photo">
        <div class="county form">
          <%= f.select :country, [["USA", "USA"], ["UK", "UK"], ["Canada", "Canada"], ["Australia", "Australia"], ["NewZealand", "Newzealand"], ["SouthAfrica", "SouthAfrica"], ["Malta", "Malta"], ["thePhilippines", "thePhilippines"]] %>
        </div>
        <div class="city form">
          <%= f.text_field :city, placeholder: "地域" %>
        </div>
        <div class="howlong form">
          <%= f.text_field :howlong, placeholder: "期間" %>
        </div>
        <div class="visa form">
          <%= f.text_field :visa, placeholder: "ビザの種類" %>
        </div>
        <div class="money form">
          <%= f.text_field :money, placeholder: "費用" %>
        </div>
        <div class="school form">
          <%= f.text_field :schoolname, placeholder: "学校名" %>
        </div>
        <div class="agent form">
          <%= f.text_field :agent, placeholder: "エージェント" %>
        </div>
        <div class="necessity form">
            <%= f.text_field :necessity, placeholder: "必需品" %>
        </div>
      </div>
      <div class="submit">
        <%= f.submit "Share", class:"submit-form"%>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% @page_title = "post by #{@post.user.name}" %>
<header>
  <div class="header-logo">
    <ul class="header-menu for-post">
      <li>
        <%= link_to("Top", root_path) %>
      </li>
      <% if user_signed_in? %>
      <li>
        <%= link_to(current_user.name, user_path(current_user.id)) %>
      </li>
      <li>
        <%= link_to("Logout", destroy_user_session_path, {method: "delete"}) %>
      </li>
      <% else %>
      <li>
        <%= link_to("Login", new_user_session_path) %> 
      <li>
        <%= link_to("Signup", new_user_registration_path) %>
      </li>
      <% end %>
    </ul>
  </div>
</header>
<div class="post-container">
  <div class="post-card">
    <div class="post-image">
      <% if @post.image_name1? %>
        <%= image_tag @post.image_name1.url %>
      <% else %>
        <%= image_tag "/no_image1.png" %>
      <% end %>
    </div>
    <div class="post-content">
      <div class="whole-content">
        <p class="question-content">country</p>
        <p class="answer-content"><%= @post.country %></p>
      </div>
      <div class="whole-content">
        <p class="question-content">city or town</p>
        <p class="answer-content"><%= @post.city %></p>
      </div>
      <div class="whole-content">
        <p class="question-content">period</p>
        <p class="answer-content"><%= @post.howlong %></p>
      </div>
      <div class="whole-content">
        <p class="question-content">visa</p>
        <p class="answer-content"><%= @post.visa %></p>
      </div>
      <div class="whole-content">
        <p class="question-content">cost</p>
        <p class="answer-content"><%= @post.money %></p>
      </div>
      <div class="whole-content">
        <p class="question-content">school</p>
        <p class="answer-content"><%= @post.schoolname %></p>
      </div>
      <div class="whole-content">
        <p class="question-content">agent</p>
        <p class="answer-content"><%= @post.agent %></p>
      </div>
      <div class="whole-content">
        <p class="question-content">necessity</p>
        <p class="answer-content"><%= @post.necessity %></p>
      </div>
        <% if current_user && @post.user_id == current_user.id %>
        <div class="can-manipulate">
          <div class="post-edit">
            <%= link_to("Edit", edit_post_path) %>
          </div>
        </div>
        <% end %>
    </div>
  </div>
  <div class="comment-field">
    <p class="comment-title"><%= @comments.count %> Comments</p>
    <div class="comment-area">
      <%= render partial: 'comments/index', locals: { comments: @comments, user: @user } %>
    </div>
    <div class="comment-create">
      <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
    </div>
    <div class="error-explanation">
      <%= render partial: 'comments/error', locals: { comment: @comment } %>
    </div>
  </div>
</div>