config/routes.rb
Rails.application.routes.draw do 

  get "contact/new" => "contact/new"
  post "contact/confirm" => "contact/confirm"
  post "contact/thanks" => "contact/thanks"

  devise_for :users

  resources :users, only: [:show]

  resources :posts, only: [:create, :new, :edit, :show, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  root "home#top"
  get "home/usa" => "home#usa"
  get "home/uk" => "home#uk"
  get "home/canada" => "home#canada"
  get "home/australia" => "home#australia"
  get "home/newzealand" => "home#newzealand"
  get "home/southafrica" => "home#southafrica"
  get "home/malta" => "home#malta"
  get "home/philippines" => "home#philippines"
  get "home/terms" => "home#terms"
  get "home/privacy" => "home#privacy"
  
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :message

  validates :message, {presence:true}
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(params[:contact].permit(:message))
    if @contact.valid?
      render("contact/confirm")
    else
      render("contact/new")
    end
  end

  def thanks
    @contact = Contact.new(params[:contact].permit(:message))    
    ContactMailer.send_mail(@contact).deliver
    render("contact/thanks")
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/confirm.html.erb
<% @page_title = "contact-confirm" %>
<header>
  <div class="header-logo">
    <ul class="header-menu for-post">
      <li>
        <%= link_to("Top", root_path) %>
      </li>
      <% if user_signed_in? %>
      <li>
        <%= link_to(current_user.name, user_path(current_user.id)) %>
      </li>
      <li>
        <%= link_to("Logout", destroy_user_session_path, {method: "delete"}) %>
      </li>
      <% else %>
      <li>
        <%= link_to("Login", new_user_session_path) %> 
      <li>
        <%= link_to("Signup", new_user_registration_path) %>
      </li>
      <% end %>
    </ul>
  </div>
</header>
<div class="contact-container">
  <div class="contact-content">
    <h3>お問い合わせ内容</h3>
    <%= form_with model: @contact, url: contact_thanks_path do |f| %>
      <div class="contact-form">
        <%= f.hidden_field :message %>
        <%= @contact.message %>
      </div>
      <div class="contact-submit">
        <%= f.submit '送信', class: "submit-contact" %>
      </div>
    <% end %>
  </div>
</div>

app/views/contact/new.html.erb
<% @page_title = "contact" %>
<header>
  <div class="header-logo">
    <ul class="header-menu for-post">
      <li>
        <%= link_to("Top", root_path) %>
      </li>
      <% if user_signed_in? %>
      <li>
        <%= link_to(current_user.name, user_path(current_user.id)) %>
      </li>
      <li>
        <%= link_to("Logout", destroy_user_session_path, {method: "delete"}) %>
      </li>
      <% else %>
      <li>
        <%= link_to("Login", new_user_session_path) %> 
      <li>
        <%= link_to("Signup", new_user_registration_path) %>
      </li>
      <% end %>
    </ul>
  </div>
</header>
<div class="contact-container">
  <div class="contact-content">
    <h3>お問い合わせ</h3>
    <%= form_with model: @contact, url: contact_confirm_path do |f| %>
      <div class="contact-form">
        <%= f.text_area :message, rows: 15, class: "contact-input", placeholder: "改善点や質問がございましたらご入力ください。"  %>
      </div>
      <div class="contact-submit">
        <%= f.submit '入力内容確認', class: "submit-contact" %>
      </div>
    <% end %>
  </div>
</div>

app/views/contact/thanks.html.erb
<header>
  <div class="header-logo">
    <ul class="header-menu for-post">
      <li>
        <%= link_to("Top", root_path) %>
      </li>
      <% if user_signed_in? %>
      <li>
        <%= link_to(current_user.name, user_path(current_user.id)) %>
      </li>
      <li>
        <%= link_to("Logout", destroy_user_session_path, {method: "delete"}) %>
      </li>
      <% else %>
      <li>
        <%= link_to("Login", new_user_session_path) %> 
      <li>
        <%= link_to("Signup", new_user_registration_path) %>
      </li>
      <% end %>
    </ul>
  </div>
</header>
<div class="thanks-container">
  <h1 class="contact-thanks">Thank you!</h1>
</div>